### ISSUE TITLE
#[test] annotations are unindented

### ISSUE THREAD

**Issue by aepsil0n** [rust-lang/rust.vim#141]
Not sure why this happens, but in my current vim setup, I have a problem, whenever I am writing tests in an inline module scope like so:

```rust
#[cfg(test)]
mod tests {
    use super::*;
```

When I am in insert mode, I will add some new lines and then hit "#" in order to write the "#[test]" annotation for the next test. When I do that, the indent will disappear and the "#" character appears at the beginning of the line.

Note that this only happens, when I hit "#" right after inserting the new line. If I add a space/tab before, the "#" character appears, where it should appear.

**Comment by chris-morgan** [comment]
This indeed used to be the case; once I did try for a few minutes to figure out what was going on, but I failed at that time, and it never annoyed me *quite* enough to chase it down at all costs.

I can’t reproduce it any more, including on rust.vim as it was at several points in the last few years, and I haven’t made any changes to my `'*indent'` settings for yonks; so I presume that it was a Vim bug which got fixed. That would tally with my vaguely-recalled confusion about the source of the bug, because I couldn’t think of any change that would have caused the regression.

I’m currently running Vim 8.0.1763. Anyone still experiencing this, try upgrading your Vim and see if that helps. (Software upgrades definitely do fix bugs sometimes! ☺) If not, then we can reopen this with more detailed diagnosis.

**Comment by aepsil0n** [comment]
Oh, guess I should have closed this a long time ago, when I realized it was not broken any more. I think I forgot that I had filed the issue.

Anyway, fyi I am on NeoVim 0.2.0 and used to have the issue on earlier versions of NeoVim. But I can't say, where in between it was fixed.

**Comment by pwoolcoc** [comment]
just FYI I am on Neovim 0.3.1 and the latest version of rust.vim, and this is still an issue for me, so just updating to the latest neovim is not enough

**Comment by mkrieger1** [comment]
It seems to be a `smartindent` "feature". While being annoyed by this I found e.g. this explanation:

https://stackoverflow.com/questions/16400261/odd-indentation-behaviour-in-vim-with-smartindent-or-filetype-indent-on

I wondered why `smartindent` was turned on although this comment in [`ftplugin/rust.vim`](https://github.com/rust-lang/rust.vim/blob/master/ftplugin/rust.vim#L44) says otherwise:

```vim
" smartindent will be overridden by indentexpr if filetype indent is on, but                                        
" otherwise it's better than nothing.                                          
setlocal smartindent nocindent 
```

And in [`indent/rust.vim`](https://github.com/rust-lang/rust.vim/blob/master/indent/rust.vim#L22) I found

```vim
" Also do indentkeys, otherwise # gets shoved to column 0 :-/
```

but `indentkeys` was not set. So I figured out the solution: I had to set

```
:filetype indent on
```

so that `indent/rust.vim` is loaded and `indentexpr` overrides `smartindent`.

**Comment by chris-morgan** [comment]
Yes, `filetype indent on` is necessary for sane indent behaviour. That’s something for users’ vimrc files—plugins like rust.vim should not fiddle with anything `:filetype`.

Aside: although the forcible-dedenting thing has been fixed, there is still a bug where attributes that will stick to column zero if already there, resisting indentation. This is due to dubious `cindent` behaviour (the docs say: “Vim puts a line in column 1 if: - It starts with '#' (preprocessor directives), if 'cinkeys' contains '#0'.”, but cinkeys doesn’t contain #0, but it still *keeps* it in column 1 if it’s already there) which I haven’t ever got round to filing a bug report about.
