### ISSUE TITLE
:RustFmt Shows Contents of File and Does Nothing

### ISSUE THREAD

**Issue by CaptainKraft** [rust-lang/rust.vim#192]
My default compiler is stable. I can run rustfmt using `rustup run nightly rustfmt main.rs` but nothing seems to happen when I use the :RustFmt command within Vim other than showing me the current file in a temporary buffer. When I close the buffer, my file is unchanged.

**Comment by MaikKlein** [comment]
I just ran into the same problem. 

`let g:rustfmt_command = "rustup run nightly rustfmt"`

This should work, but `:RustFmtRange` still doesn't.

**Comment by CaptainKraft** [comment]
Thanks @MaikKlein

**Comment by MaikKlein** [comment]
I had the same problem, I currently just do this

`map <leader>mf :mark '<CR>:! rustup run nightly rustfmt %<CR>'':e<CR>`

**Comment by mb720** [comment]
Thanks @MaikKlein! The following, shorter, variant works fine for me as well:

`map <leader>mf :mark '<CR>:! rustfmt %<CR>''`

**Comment by da-x** [comment]
Thanks everyone! The RustInfo was helpful :) It looks that the cutoff between having to specify `--emit=files` and `--write-mode=overwrite` is between version 0.8.1 and 0.8.2 (nightly). 

I corrected the logic for rust.vim to be able to work with any rustfmt version (if it's incorrect please tell me). So you can try master and tell how it goes.

**Comment by da-x** [comment]
Ok, `master` was update now.

**Comment by mb720** [comment]
Works great. Thanks @da-x! :+1:

**Comment by Deedasmi** [comment]
I'm still getting this. `:RustFmt` wither either rustfmt or rustup run nightly rustfmt just shows a plain buffer of the same file and nothing happens when it's closed.

**Comment by da-x** [comment]
Yes, I saw it too - it may happen when parsing of rustfmt errors fails. Recently this parsing was fixed but not completely.

I have plans to make overhaul of that old code to make it more lenient. Opening until it happens.

**Comment by da-x** [comment]
Issue should be fixed now in master.

**Comment by lipeng31** [comment]
> Issue should be fixed now in master.

I think the problem is still open for now.

I'm using Vim 8.1 on macOS, rustfmt 1.0.0-nightly (1cc61cfc 2018-11-19).

**Comment by StoicDeveloper** [comment]
I'm getting this issue. I'm on the current master of this plugin, with cargo 1.61.0

Relevant .vimrc lines:
`
let g:rustfmt_command = "rustup run stable rustfmt"
let g:ale_linters = {}
let g:ale_linters.rust = ['cargo', 'rls']
let g:ale_rust_rls_toolchain = 'stable'

let g:rustfmt_autosave = 1

" Fix files with prettier, and then ESLint.
let b:ale_fixers = ['prettier', 'eslint', 'rustfmt']`

My :RustInfo output:
`rust.vim Global Variables:                                                                                                                                                                                         
let g:ftplugin_rust_source_path = v:null                                                                                                                                                                           
let g:loaded_syntastic_rust_cargo_checker = v:null                                                                                                                                                                 
let g:loaded_syntastic_rust_filetype = v:null                                                                                                                                                                      
let g:loaded_syntastic_rust_rustc_checker = v:null                                                                                                                                                                 
let g:rust_bang_comment_leader = v:null                                                                                                                                                                            
let g:rust_cargo_avoid_whole_workspace = v:null                                                                                                                                                                    
let g:rust_clip_command = v:null                                                                                                                                                                                   
let g:rust_conceal = v:null                                                                                                                                                                                        
let g:rust_conceal_mod_path = v:null                                                                                                                                                                               
let g:rust_conceal_pub = v:null                                                                                                                                                                                    
let g:rust_fold = v:null                                                                                                                                                                                           
let g:rust_last_args = v:null                                                                                                                                                                                      
let b:rust_last_args = []                                                                                                                                                                                          
let g:rust_last_rustc_args = v:null                                                                                                                                                                                
let b:rust_last_rustc_args = []                                                                                                                                                                                    
let g:rust_original_delimitMate_excluded_regions = v:null                                                                                                                                                          
let g:rust_playpen_url = v:null                                                                                                                                                                                    
let g:rust_prev_delimitMate_quotes = v:null                                                                                                                                                                        
let g:rust_recent_nearest_cargo_tol = v:null                                                                                                                                                                       
let g:rust_recent_root_cargo_toml = v:null                                                                                                                                                                         
let g:rust_recommended_style = v:null                                                                                                                                                                              
let g:rust_set_conceallevel = v:null                                                                                                                                                                               
let g:rust_set_conceallevel=1 = v:null                                                                                                                                                                             
let g:rust_set_foldmethod = v:null                                                                                                                                                                                 
let g:rust_set_foldmethod=1 = v:null                                                                                                                                                                               
let g:rust_shortener_url = v:null                                                                                                                                                                                  
let g:rustc_makeprg_no_percent = v:null                                                                                                                                                                            
let g:rustc_path = v:null                                                                                                                                                                                          
let g:rustfmt_autosave = 1                                                                                                                                                                                         
let g:rustfmt_autosave_if_config_present = v:null                                                                                                                                                                  
let g:rustfmt_command = 'rustup run stable rustfmt'                                                                                                                                                                
let g:rustfmt_emit_files = 1                                                                                                                                                                                       
let g:rustfmt_fail_silently = 0                                                                                                                                                                                    
let g:rustfmt_options = ''                                                                                                                                                                                         
let g:syntastic_extra_filetypes = ['rust']                                                                                                                                                                         
let g:syntastic_rust_cargo_fname = v:null                                                                                                                                                                          
rustfmt 1.4.38-stable (fe5b13d 2022-05-18)                                                                                                                                                                         
rustc 1.61.0 (fe5b13d68 2022-05-18)                                                                                                                                                                                
cargo 1.61.0 (a028ae4 2022-04-29)  `

Still, running :RustFmt does nothing, the mapping fix mentioned above also doesn't work.
